name: Run Tests
on: [ push, pull_request ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 17 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Build application
      - name: Test and Build
        run: ./gradlew build
